### ISSUE TITLE
可以识别歌词信息吗

### ISSUE THREAD

**Issue by echunun** [MAraragi/MusicalScoreRecognition#3]
感谢工作

**Comment by MAraragi** [comment]
> 感谢工作

xd我这个代码不支持识别歌词信息哈，我代码的思路是先把图像按照小节线分段，然后一段段识别。分段的时候会先确定每个小节线的位置，然后按照竖直方向来分组。
分组过后一般来说就可以得到每个小节的纵向位置，如果要使其能够识别歌词信息的话，可以在得到每个小节的纵向位置后，将小节间的图像片段截取出来，找一些OCR的脚本来识别一下，然后把得到的文本跟小节匹配起来就好。
最后的保存格式感觉有点麻烦，歌词应该不能存在midi文件里面，感觉xd需要的话可以用json或者xml这种通用一点的格式来存。

**Comment by MAraragi** [comment]
> 感谢工作

xd可以在`recognition.py`的第`108`行把`self.sections`打印出来看看，我记得这个里面存的是识别得到的各个小节的坐标。
